In [18]:
import numpy as np
a = np.array([[56.0, 0.0, 4.4, 68.0], [1.2, 104.0, 52.0, 8.0],[1.8, 135.0, 99.0, 0.9]])
a

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [19]:
cal = a.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [22]:
val = 100 * a / cal.reshape(1, 4)
val

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [37]:
a = np.array([[2, 1, 5], [4, 1, 1]])
b = np.array([[2],[1]])     
#print(a.shape)
#print(b.shape)
c = np.dot(a, b)
c.shape

(2, 3)
(2, 1)


ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)